### ISSUE TITLE
Episode 0228 - Composable Navigation: Destinations sample code not found

### ISSUE THREAD

**Issue by MojtabaHs** [pointfreeco/episode-code-samples#137]
Hi, first of all, thanks for the effort and fantastic framework and tutorial series you prepared.
 
This issue is very often when you guys upload a new episode and link to a sample that does not exist on the GitHub. It seems that it is a manual process and you forgot it. Maybe making an automated task will resolve this. 🙌🏻

> The 'pointfreeco/episode-code-samples' repository doesn't contain the '0228-composable-navigation-pt7' path in 'main'. 

[Link to the sample](https://github.com/pointfreeco/episode-code-samples/tree/main/0228-composable-navigation-pt7)

**Comment by stephencelis** [comment]
Pushed, thanks!
