### ISSUE TITLE
Episode 109 sheet show twice when item name changed

### ISSUE THREAD

**Issue by ibcylon** [pointfreeco/episode-code-samples#148]
Episode 109 - sheet shows twice when item name changed and cancel or save button tapped
minimum deploy target - 17.0

**Comment by stephencelis** [comment]
@ibcylon SwiftUI can write to a binding even after it's been `nil`ed out, which in this case causes it to re-present. This is a scenario that the resulting [swiftui-navigation](https://github.com/pointfreeco/swiftui-navigation) library works around, but the episode code sample does not :)
