### ISSUE TITLE
Episode Structs and Enums

### ISSUE THREAD

**Issue by nuno-vieira** [pointfreeco/episode-code-samples#23]
`let choice: (id: Int | param: String) = .param("Blob")`

How can this compile? Am I missing something? Swift doesn't support this right?

**Comment by stephencelis** [comment]
It doesn't 😄

Check out this part of the episode where we have a long discussion about what a theoretical anonymous sum type _might_ look like in Swift:

https://www.pointfree.co/episodes/ep51-structs-enums#t1029
