### ISSUE TITLE
Dead Link: episodes/ep28-html-dsl

### ISSUE THREAD

**Issue by marc-medley** [pointfreeco/episode-code-samples#24]
Page: https://github.com/pointfreeco/episode-code-samples/tree/master/0028-html-dsl 

Broken Link: "An HTML DSL" https://www.pointfree.co/episodes/ep28-html-dsl

Working Link: https://www.pointfree.co/episodes/ep28-an-html-dsl

**Comment by stephencelis** [comment]
Fixed, thanks!
