### ISSUE TITLE
Episode 84 crash on iOS 13

### ISSUE THREAD

**Issue by AlexisQapa** [pointfreeco/episode-code-samples#42]
Hi,

The test helper introduced in this week episode crash on iOS 13.3 (today Xcode update) while running tests on the Counter module.
This is due to the subscription being discarded, saving it to a let solves the issue but still raises an unused warning.

**Comment by stephencelis** [comment]
Thanks for the report! Looks like things are ever-evolving :)

**Comment by mbrandonw** [comment]
Thanks for the bug report! I just pushed 1fc362e. I decided to accumulate all of the cancellables into an array instead of having the warning. We will have future iteration on this assert helper, because it's not 100% correct right now.
