### ISSUE TITLE
Unit test don't compile

### ISSUE THREAD

**Issue by toddwbates** [pointfreeco/episode-code-samples#57]
I am unable to run the unit tests from the PrimeTime target because CounterTests and PrimeTime tests don't compile.

**Comment by stephencelis** [comment]
Hey @toddwbates! Can you give us more information? Which episode are you referring to? Depending on the episode, unit tests may not be in a building state.

**Comment by stephencelis** [comment]
Ah I see now. Episode 96? I think we're missing a bit of the episode code. I'll fix shortly, thanks!

**Comment by toddwbates** [comment]
Yes, Episode 96. I was just double checking;-)

**Comment by stephencelis** [comment]
Fixed! Thanks for the heads up!
