### ISSUE TITLE
Unable to Access Source Code for Designing Dependencies: Core Location

### ISSUE THREAD

**Issue by nickkohrn** [pointfreeco/episode-code-samples#66]
When attempting to access [Designing Dependencies: Core Location](https://github.com/pointfreeco/episode-code-samples/blob/main/0113-designing-dependencies-pt4) (list item 113) in [`README.md`](https://github.com/pointfreeco/episode-code-samples/blob/main/README.md), a `404` is encountered.

![CleanShot 2020-08-21 at 08 23 24](https://user-images.githubusercontent.com/5864877/90890257-9cdc6100-e387-11ea-891c-cfe4ede4e448.gif)

Additionally, when attempting to access the source code, the source code for Designing Dependencies: Reachability (list item 112) is returned.

![CleanShot 2020-08-21 at 08 25 39](https://user-images.githubusercontent.com/5864877/90890413-f3499f80-e387-11ea-919e-db06901dee1f.gif)

**Comment by stephencelis** [comment]
Sorry about that! Fixed it a bit ago but missed this issue.
