### ISSUE TITLE
Issue with running TCA on an M1 device.

### ISSUE THREAD

**Issue by CrystalKnightCodes** [pointfreeco/episode-code-samples#78]
I am building an app that uses TCA, and I recently purchased the new iMac with the M1.  I can successfully build and run the project on my MacBook Pro, but when I try to run the same code, same branch, same device (all updated to the same versions), I get a build error on the M1.
macOS Big Sur 11.3.1
Xcode 12.5
iOS: 14.5.1
[Code](https://gist.github.com/CrystalKnightCodes/2c86d57c8f3f504e392b844c50392ec3)

Error message on line 23: 
Cannot convert value of type 'Store<IdentifiedArray<UUID, HotlistSelection>, HotlistSelector.ListActionData>' (aka 'Store<IdentifiedArray<UUID, HotlistSelection>, (id: UUID, action: HotlistManagementAction.List)>') to expected argument type 'Store<IdentifiedArray<UUID, HotlistSelection>, (UUID, HotlistManagementAction.List)>'

I suspect this has to do with building the library on ARM.  Does anyone have a workaround?

**Comment by stephencelis** [comment]
Hi @CrystalKnightCodes! Sorry for the delay. This is our episode code samples repo, which gets a little less attention than TCA's repo proper.

If you're still having an issue, can move the discussion there? If you believe it's a bug in the repo, please file an issue, and if you're having trouble getting some code to work, please open a GitHub Q&A discussion.

**Comment by stephencelis** [comment]
I'm going to close this out for now, but please update us if you need anything!
