### ISSUE TITLE
0148 Derived Behaviour - Animation

### ISSUE THREAD

**Issue by hisavali** [pointfreeco/episode-code-samples#79]
**Summary:**
- Removal of the last Counter Row Cell adds the new cell automatically (see frame at 04th second) (At least that's how it looks)
- Removal of one of the middle Counter Row cells results in App Crash (see frame at 07th second)

**Root Cause:** 

```
"CounterRowAction.removeButtonTapped" was received by a "forEach" reducer at id 332A618F-1D42-4463-9DB0-5839D002FF82 when its state contained no element at this id. This is generally considered an application logic error, and can happen for a few reasons:

* This "forEach" reducer was combined with or run from another reducer that removed the element at this id when it handled this action. To fix this make sure that this "forEach" reducer is run before any other reducers that can move or remove elements from state. This ensures that "forEach" reducers can handle their actions for the element at the intended id.

* An in-flight effect emitted this action while state contained no element at this id. It may be perfectly reasonable to ignore this action, but you also may want to cancel the effect it originated from when removing an element from the identified array, especially if it is a long-living effect.

* This action was sent to the store while its state contained no element at this id. To fix this make sure that actions for this reducer can only be sent to a view store when its state contains an element at this id. In SwiftUI applications, use "ForEachStore".
--- 
```

**Alternative:**
- Action sent with animation `viewStore.send(.removeButtonTapped, animation: .default)` causes the issue.
If action is sent with `viewStore.send(.removeButtonTapped)`, app behaves as expected.

**File**

https://user-images.githubusercontent.com/2108707/120992187-fa6b5e00-c79f-11eb-9970-6499238ab1fe.mov

**Comment by stephencelis** [comment]
We believe this is a known SwiftUI bug, but have tried to work around it in recent versions of TCA. When I update to latest package versions (TCA 0.24.0 as of writing this) things appear to behave as they should (tested in Xcode 13 beta 5).

Can you confirm?

**Comment by stephencelis** [comment]
Hi @hisavali! I'm going to close this out, but if you believe there's still an issue in TCA, please do file a ticket with a reproduction there. Thanks again!
